"""
Generate Sample PDF Risk Report
==============================
Generates a professional sample PDF incident and credit risk report using reportlab.
Saves the report to docs/sample_risk_report.pdf.

Usage:
  python scripts/generate_sample_pdf.py
"""
import os
import sys

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
except ImportError:
    print("reportlab is required to generate the sample PDF report.")
    print("Please install it using: pip install reportlab")
    sys.exit(1)

def build_pdf(filename="docs/sample_risk_report.pdf"):
    # Ensure output directory exists
    os.makedirs(os.path.dirname(filename), exist_ok=True)
    
    doc = SimpleDocTemplate(
        filename,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#1a365d'),
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#4a5568'),
        spaceAfter=30
    )
    
    h1_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=colors.HexColor('#2b6cb0'),
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#2d3748'),
        spaceAfter=10
    )
    
    callout_style = ParagraphStyle(
        'CalloutText',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor('#9b2c2c'),
    )

    story = []
    
    # --- Header ---
    story.append(Paragraph("CYBERRISK PLATFORM", ParagraphStyle('TopPre', fontName='Helvetica-Bold', fontSize=10, leading=12, textColor=colors.HexColor('#718096'), spaceAfter=5)))
    story.append(Paragraph("Incident Assessment & Financial Exposure Report", title_style))
    story.append(Paragraph("Generated by 5-Agent LangGraph Orchestrator & Risk Engine", subtitle_style))
    story.append(Spacer(1, 10))
    
    # --- Incident metadata block ---
    meta_data = [
        [Paragraph("<b>Incident ID:</b>", body_style), Paragraph("INC-E3A9C8D4", body_style), Paragraph("<b>Assessment Date:</b>", body_style), Paragraph("2026-07-11 00:30:15 UTC", body_style)],
        [Paragraph("<b>Target Facility:</b>", body_style), Paragraph("Power Plant (device-02)", body_style), Paragraph("<b>Location:</b>", body_style), Paragraph("Zone-B / Grid East", body_style)],
        [Paragraph("<b>Attack Signature:</b>", body_style), Paragraph("Denial of Service (DoS)", body_style), Paragraph("<b>Incident Severity:</b>", body_style), Paragraph("<font color='#e53e3e'><b>CRITICAL</b></font>", body_style)],
        [Paragraph("<b>Containment State:</b>", body_style), Paragraph("<font color='#38a169'><b>ISOLATED</b> (Network Quarantine)</font>", body_style), Paragraph("<b>Isolation Port:</b>", body_style), Paragraph("MQTT Channel 1883", body_style)]
    ]
    t_meta = Table(meta_data, colWidths=[1.5*inch, 2.0*inch, 1.5*inch, 2.0*inch])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f7fafc')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 20))
    
    # --- Technical findings ---
    story.append(Paragraph("1. Technical Incident Narrative", h1_style))
    story.append(Paragraph(
        "At approximately 00:30:15 UTC, the telemetry gateway flagged critical sensor anomalies from Device 02 (Power Plant). "
        "The <b>Detector Agent</b> running local Random Forest Classifier computed an anomaly score of <b>0.941</b>, indicating a high-confidence attack vector. "
        "The state was dispatched to the <b>Classifier Agent</b> which analyzed telemetry signature characteristics: temperature spiked to 120°C and pressure breached normal thresholds at 380bar, which is a classic signature for a Denial of Service (DoS) load attack on turbine control units.",
        body_style
    ))
    story.append(Paragraph(
        "The <b>Isolator Agent</b> triggered network micro-segmentation commands, issuing a quarantine payload to the MQTT broker to isolate Device 02 from the main industrial network. "
        "This containment action successfully prevented lateral movement to nearby SCADA equipment.",
        body_style
    ))
    story.append(Spacer(1, 15))
    
    # --- Financial exposure table ---
    story.append(Paragraph("2. Financial Blast-Radius Quantification", h1_style))
    story.append(Paragraph(
        "The <b>Risk Quantifier Agent</b> mapped the technical parameters (downtime duration and device type) into a structured economic loss model. "
        "Because the power plant has a critical grid-stabilization SLA, downstream penalties accumulate rapidly. Fines were calculated according to NERC CIP regulatory enforcement schedules.",
        body_style
    ))
    
    financial_data = [
        [Paragraph("<b>Cost Component</b>", body_style), Paragraph("<b>Calculation Method / Rate</b>", body_style), Paragraph("<b>Estimated Loss (USD)</b>", body_style)],
        [Paragraph("Downtime Operating Losses", body_style), Paragraph("8.0 Hours @ $500,000.00 / Hour", body_style), Paragraph("$4,000,000.00", body_style)],
        [Paragraph("SLA Grid Penalty", body_style), Paragraph("15% of Downtime Cost", body_style), Paragraph("$600,000.00", body_style)],
        [Paragraph("NERC CIP Regulatory Fine", body_style), Paragraph("Severity Level 2 Schedule Lookup", body_style), Paragraph("$2,000,000.00", body_style)],
        [Paragraph("<b>Total Exposure</b>", body_style), Paragraph("<b>Sum of Losses</b>", body_style), Paragraph("<b>$6,600,000.00</b>", body_style)]
    ]
    t_fin = Table(financial_data, colWidths=[2.2*inch, 3.0*inch, 1.8*inch])
    t_fin.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#ebf8ff')),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#cbd5e0')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('BACKGROUND', (0,-1), (-1,-1), colors.HexColor('#edf2f7')),
        ('ALIGN', (2,0), (2,-1), 'RIGHT'),
    ]))
    story.append(t_fin)
    story.append(Spacer(1, 20))
    
    # --- Credit Risk Callout box ---
    story.append(Paragraph("3. Bank Credit Risk Assessment", h1_style))
    
    credit_data = [
        [
            Paragraph("<b>CREDIT RISK ALERT: CRITICAL RISK FLAG</b><br/><br/>"
                      "The estimated total exposure of $6,600,000 breaches the lender's $2,000,000 warning threshold.<br/>"
                      "<b>Recommendation:</b> Initiate immediate covenant review. The operator of the facility exhibits elevated debt service risk due to expected working capital depletion. Verify operator's cybersecurity liability insurance coverage and check if the isolated device has been restored via secondary secure bootstrap.", callout_style)
        ]
    ]
    t_cred = Table(credit_data, colWidths=[7.0*inch])
    t_cred.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#fff5f5')),
        ('BOX', (0,0), (-1,-1), 1.5, colors.HexColor('#feb2b2')),
        ('PADDING', (0,0), (-1,-1), 12),
    ]))
    story.append(t_cred)
    story.append(Spacer(1, 20))
    
    # Footer-like signature
    story.append(Paragraph("Report verified by <i>Aegis Reporter Agent</i>. Compliance standard: NIST SP 800-61.", ParagraphStyle('FooterStyle', fontName='Helvetica-Oblique', fontSize=8, leading=10, textColor=colors.HexColor('#718096'))))
    
    doc.build(story)
    print(f"Sample PDF report successfully generated at: {filename}")

if __name__ == "__main__":
    # If run standalone, use root docs/
    build_pdf()
